	LOAD_MIO0(        /*seg*/ 0x07, _wdw_segment_7SegmentRomStart, _wdw_segment_7SegmentRomEnd),
    LOAD_MODEL_FROM_GEO(MODEL_WDW_WATER_LEVEL_DIAMOND,           water_level_dimond_geo),
    AREA(1, castle_grounds_area_1_level),
        OBJECT(/*model*/ MODEL_NONE, /*pos*/     0,    0,     0, /*angle*/ 0,   0, 0, /*behParam*/ 0x00000000, /*beh*/ bhvInitializeChangingWaterLevel),
		OBJECT(0x38, -707, 573, -13, 0, 0, 0, 0, bhvWaterLevelDiamond),
		OBJECT(0x38, 668, -306, 0, 0, 0, 0, 0, bhvWaterLevelDiamond),
		OBJECT(0x38, 121, 70, -137, 0, 0, 0, 0, bhvWaterLevelDiamond),
		TERRAIN(castle_grounds_area_1_collision),
		MACRO_OBJECTS(castle_grounds_area_1_Area_macro_objs),
		SET_BACKGROUND_MUSIC(0x00, SEQ_LEVEL_GRASS),
		TERRAIN_TYPE(TERRAIN_GRASS),
	END_AREA(),

