    LOAD_MIO0(        /*seg*/ 0x07, _wdw_segment_7SegmentRomStart, _wdw_segment_7SegmentRomEnd),
    LOAD_MODEL_FROM_GEO(MODEL_WDW_WATER_LEVEL_DIAMOND,           water_level_dimond_geo),
    AREA(1, castle_grounds_area_1_level),
        OBJECT(/*model*/ MODEL_NONE, /*pos*/     0,    0,     0, /*angle*/ 0,   0, 0, /*behParam*/ 0x00000000, /*beh*/ bhvInitializeChangingWaterLevel),
        OBJECT(0x38, 682, 465, 0, 0, 0, 0, 0, bhvWaterLevelDiamond),
        OBJECT(0x38, -682, -435, 0, 0, 0, 0, 0, bhvWaterLevelDiamond),
        OBJECT(/*model*/ MODEL_NONE, /*pos*/ 0, 0, 160, /*angle*/ 0,   0, 0, /*behParam*/ 0x000C0000, /*beh*/ bhvFadingWarp),
        WARP_NODE(/*id*/ 0x0C, /*destLevel*/ LEVEL_CASTLE_GROUNDS, /*destArea*/ 0x02, /*destNode*/ 0x0B, /*flags*/ WARP_NO_CHECKPOINT),
        TERRAIN(castle_grounds_area_1_collision),
        // MACRO_OBJECTS(castle_grounds_area_1_Area_macro_objs),
        SET_BACKGROUND_MUSIC(0x00, SEQ_LEVEL_GRASS),
        TERRAIN_TYPE(TERRAIN_GRASS),
    END_AREA(),
    AREA(2, castle_grounds_area_2_level),
        OBJECT(/*model*/ MODEL_NONE, /*pos*/     0,    0,     0, /*angle*/ 0,   0, 0, /*behParam*/ 0x00000000, /*beh*/ bhvInitializeChangingWaterLevel),
        OBJECT(0x38, 682, 465, 700, 0, 0, 0, 0, bhvWaterLevelDiamond),
        OBJECT(0x38, -682, -435, 700, 0, 0, 0, 0, bhvWaterLevelDiamond),
        OBJECT(/*model*/ MODEL_NONE, /*pos*/ 0, 100, 600, /*angle*/ 0,   0, 0, /*behParam*/ 0x000B0000, /*beh*/ bhvFadingWarp),
        WARP_NODE(/*id*/ 0x0B, /*destLevel*/ LEVEL_CASTLE_GROUNDS, /*destArea*/ 0x01, /*destNode*/ 0x0C, /*flags*/ WARP_NO_CHECKPOINT),
        TERRAIN(castle_grounds_area_2_collision),
        // MACRO_OBJECTS(castle_grounds_area_2_Area_macro_objs),
        SET_BACKGROUND_MUSIC(0x00, SEQ_LEVEL_GRASS),
        TERRAIN_TYPE(TERRAIN_GRASS),
    END_AREA(),
